version: "3.8"

services:
  app:
    build:
      context: ../go_viet_tran1
      dockerfile: Dockerfile
    container_name: go_app
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    networks:
      - app-network

  nextjs:
    build:
      context: ../nextjs_app
      dockerfile: Dockerfile
    container_name: nextjs_app
    networks:
      - app-network

  nginx:
    image: nginx:1.23.3
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - nextjs
    networks:
      - app-network

  mysql:
    image: mysql:8.1.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
